"""Builds new-faces-2026-10.json: the 95 new faces Claude cast on 2026-10-07/08.

Facts here were invented by Claude with the Owner's blanket approval (2026-10-08:
"籍贯这些信息你编就行，有点意思就行"). They are placeholders for a first public
roster and may be replaced in later versions. Images live in
media-pack/library/claude-casting-2026-10-07/final/CC-xxx.png (gitignored).
Run: python3 media-pack/casting/new-faces-2026-10.py
"""
import json, os, re, unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))

# cc, nameZh, nameEn, origin zh, origin en, tagline zh, tagline en, voice lang, voice brief (zh), self-intro line
R = [
 # ---------- East Asian women ----------
 ("001","林小满","Lin Xiaoman","黑龙江哈尔滨","Harbin, Heilongjiang","个子小，嗓门大，东北姑娘。","Small frame, big voice. A Harbin girl through and through.","zh",
  "23岁东北姑娘，普通话带一点东北味，声音清亮脆生，语速快，爱笑，说话直来直去。",
  "大家好啊，我叫林小满，哈尔滨的，今年二十三。别看我个儿小，嗓门可一点不小，片场喊一嗓子全组都能听见。我最想演那种表面乖乖的、心里一肚子小主意的人。有戏找我，保证不掉链子！"),
 ("006","卫青禾","Wei Qinghe","辽宁大连","Dalian, Liaoning","高，瘦，说话慢，眼神很稳。","Tall, lean and unhurried, with a very steady gaze.","zh",
  "31岁女性，普通话标准略带北方口音，声音偏低、沉稳、干净，语速慢，句子之间有停顿，冷静克制。",
  "我叫卫青禾，大连人，三十一岁。我说话一向比较慢，不是反应慢，是想清楚了再说。朋友都说我适合演医生、律师，或者那种什么都不说、最后一句话把大家镇住的人。我挺喜欢这种角色的。"),
 ("011","胡桂芬","Hu Guifen","湖北武汉","Wuhan, Hubei","酒窝很深，笑声比人先到。","Deep dimples. Her laugh arrives before she does.","zh",
  "45岁武汉女人，普通话带明显武汉口音，声音圆润洪亮，热情泼辣，语速快，笑声多，像街口热干面店的老板娘。",
  "哎哟，我是胡桂芬，武汉的，今年四十五咯。我这个人啊，就是爱笑，一笑脸上两个酒窝。以前在街口帮我姐守过早点摊，什么人都见过。你要我演个热心肠的大姐、厉害的老板娘，那是手到擒来！"),
 ("016","常淑兰","Chang Shulan","山西太原","Taiyuan, Shanxi","下巴方，脾气硬，心最软。","Square jaw, hard temper, soft heart.","zh",
  "62岁山西女性，普通话带山西口音，声音略沙、有力，说话干脆利落，带点严厉，但尾音有温度。",
  "我叫常淑兰，太原人，六十二了。年轻时在纺织厂当过车间主任，嗓门是那时候练出来的。我这人脾气是硬了点，可谁家有事我第一个到。演婆婆、演奶奶、演居委会主任，我都行。"),
 ("021","程小鹿","Cheng Xiaolu","湖南长沙","Changsha, Hunan","眉毛浓，嘴巴大，鼻梁上有几颗雀斑。","Heavy brows, a wide grin and a few freckles across the nose.","zh",
  "27岁长沙女孩，普通话带一点湖南口音，声音明亮有活力，爱开玩笑，语速快，情绪外放。",
  "嗨，我是程小鹿，长沙妹子，二十七岁。我嘴巴大，笑起来可能有点夸张，不过大家都说看我笑会被传染。我最想演那种冒冒失失、但关键时刻特别靠谱的朋友。对了，吃辣我是认真的！"),
 ("026","柳曼青","Liu Manqing","上海","Shanghai","尖下巴，上挑眼，嘴角一颗痣。","Pointed chin, upturned eyes, a beauty mark above her lip.","zh",
  "38岁上海女性，普通话带一点上海口音，声音柔而有锋芒，语调精致，偶尔带点调侃，语速中等。",
  "侬好，我是柳曼青，上海人，三十八岁。很多人第一眼觉得我不好接近，大概是因为这双眼睛吧。其实我挺爱笑的。我适合演精明的职场女性，也可以演看起来厉害、其实很怕孤单的人。"),
 ("031","邹美华","Zou Meihua","江西南昌","Nanchang, Jiangxi","圆脸，细边眼镜，一笑眼睛就没了。","Round face, thin glasses, eyes that vanish when she smiles.","zh",
  "55岁南昌女性，普通话带江西口音，声音温和敦厚，说话慢悠悠，像中学数学老师，偶尔絮叨。",
  "大家好，我叫邹美华，南昌人，五十五岁。我以前在中学教了二十多年数学，所以说话可能有点慢、有点啰嗦，你们多担待。我演老师肯定像，演那种操心全家的妈妈，也不在话下。"),
 ("036","钱素梅","Qian Sumei","江苏苏州","Suzhou, Jiangsu","白发盘得一丝不乱，脸上一颗小痣。","White hair pinned in a perfect bun, a small mole on her cheek.","zh",
  "71岁苏州老太太，普通话带吴语软糯口音，声音轻柔、慢、带笑，气息略弱但清楚，慈祥。",
  "我叫钱素梅，苏州人，今年七十一岁啦。我说话慢，你们不要急哦。年轻时候在评弹团里打过杂，听了一辈子的好故事。现在能自己来演戏，我开心得不得了。演外婆、演老邻居，我最拿手。"),
 ("041","江一帆","Jiang Yifan","山东青岛","Qingdao, Shandong","短寸头，眉毛硬，跑得比谁都快。","Undercut, strong brows, faster than anyone on the lot.","zh",
  "20岁青岛女生，普通话带一点山东口音，声音中性偏低，干脆利落，有运动员的爽快劲儿。",
  "我叫江一帆，青岛的，二十岁，以前练过五年短跑。我头发短，好多人第一眼以为我是男生，我无所谓。动作戏、跑戏、摔戏，你尽管来，我不用替身。文戏我也在练，真的。"),
 ("046","叶书宁","Ye Shuning","浙江杭州","Hangzhou, Zhejiang","长脸，大眼睛，下巴一颗小痣。","Long face, big eyes, a tiny mole on the chin.","zh",
  "34岁杭州女性，普通话标准、柔和，声音温润，语气平静带一点书卷气，语速中等偏慢。",
  "你好，我是叶书宁，杭州人，三十四岁。我平时喜欢逛书店、喝茶，朋友说我身上有股安静劲儿。我想演那种看起来温温柔柔，心里有自己主意的女人，比如开书店的老板，或者一个守着秘密的姐姐。"),
 ("051","孟昭华","Meng Zhaohua","辽宁沈阳","Shenyang, Liaoning","肩膀宽，鬓角白，站着就像个领导。","Broad shoulders, greying temples. She stands like the boss.","zh",
  "49岁沈阳女性，普通话带东北口音，声音低沉有力，气场强，说话干脆有分量，偶尔幽默。",
  "我叫孟昭华，沈阳人，四十九。个子高，肩膀宽，往那一站，大家都以为我是领导。其实我挺能逗的。演厂长、演局长、演那种说一不二的大家长，我有经验。不过你要让我演个搞笑的，我也接得住。"),
 ("056","甘小棠","Gan Xiaotang","四川成都","Chengdu, Sichuan","苹果脸，小圆鼻，说话软软的。","Apple cheeks, a button nose and a soft, sweet voice.","zh",
  "26岁成都女孩，普通话带明显四川口音，声音甜软，慢悠悠的，爱撒娇，有点憨。",
  "大家好，我是甘小棠，成都的，二十六岁。我说话可能有点慢，因为成都人都比较巴适嘛。我脸圆圆的，好多人说我像个汤圆。我想演那种憨憨的、可爱的、偶尔吃货的角色，演得肯定很真实。"),
 ("061","严若琳","Yan Ruolin","北京","Beijing","额头高，眉毛细，发髻扎得一丝不苟。","High forehead, fine brows, hair pulled into a tight low bun.","zh",
  "41岁北京女性，普通话字正腔圆带一点京味，声音清冷、精确，语速平稳，带点距离感。",
  "我是严若琳，北京人，四十一岁。我说话比较直接，不太爱绕弯子。很多人觉得我冷，其实我只是认真。我适合演严格的主编、医院的主任，或者那种你以为是反派、最后才发现她一直在帮你的人。"),
 ("066","牛凤英","Niu Fengying","河南郑州","Zhengzhou, Henan","红褐色卷发，眉边一颗痣，笑纹很深。","Red-brown perm, a mole by her brow and deep laugh lines.","zh",
  "58岁郑州女性，普通话带河南口音，声音敞亮，爱说爱笑，带点俏皮，像广场舞领队。",
  "中！我叫牛凤英，郑州的，五十八了。我是我们小区广场舞的领队，嗓门大，人缘好。这头卷发是我自己染的，好看不？演热心大妈、演媒婆、演爱管闲事的邻居，我张嘴就来。"),
 ("071","夏知遥","Xia Zhiyao","福建厦门","Xiamen, Fujian","两边眉毛不一样高，看起来总在想事情。","One brow sits higher, so she always looks like she's thinking.","zh",
  "29岁厦门女性，普通话带一点闽南口音，声音轻柔偏气声，语速慢，有点神秘感和文艺感。",
  "我叫夏知遥，厦门人，二十九岁。我左边眉毛比右边高一点，所以总有人问我是不是在怀疑他。其实我只是在发呆。我喜欢海，也喜欢有点奇怪的故事。如果有悬疑片，我很想演那个知道真相的人。"),
 ("076","陶桂香","Tao Guixiang","江苏南京","Nanjing, Jiangsu","灰黑卷发，笑起来像过年。","Grey-black curls and a smile like Spring Festival.","zh",
  "66岁南京老太太，普通话带南京口音，声音温暖、略沙，慢条斯理，絮絮叨叨很亲切。",
  "我叫陶桂香，南京人，六十六岁。退休以后天天给孙子做饭，现在孙子上大学了，我闲不住，就来演戏了。我做的盐水鸭可好吃了。演奶奶、演外婆、演菜市场的老阿姨，你们放心交给我。"),
 ("081","冯野","Feng Ye","内蒙古呼和浩特","Hohhot, Inner Mongolia","颧骨高，下颌宽，短得利落的头发。","High cheekbones, a wide jaw and a sharp pixie crop.","zh",
  "36岁内蒙古女性，普通话标准带一点北方口音，声音沉稳有力，中低音，干脆，有野性和力量感。",
  "我叫冯野，呼和浩特人，三十六岁。名字里这个野字，是我爸起的，说希望我像草原上的风。我骑马、射箭都会一点。我想演那种独来独往、靠自己闯出来的女人，警察、向导、赛车手，都行。"),
 ("086","方小语","Fang Xiaoyu","安徽合肥","Hefei, Anhui","细框眼镜，齐刘海，说话轻声细语。","Thin glasses, straight bangs and a quiet voice.","zh",
  "24岁合肥女生，普通话标准，声音轻柔细腻，有点害羞，语速偏慢，偶尔紧张地笑。",
  "大家好，我叫方小语，合肥人，二十四岁。我平时话不多，说话也比较小声，嗯……熟了以后就好了。我研究生读的是图书馆学。我觉得我很适合演那种安静的、但观察力特别强的女孩子。"),
 ("091","鲁红梅","Lu Hongmei","山东济南","Jinan, Shandong","方脸浓眉，下巴一道小疤，干活利索。","Square face, thick brows, a small scar on the chin. Gets things done.","zh",
  "52岁济南女性，普通话带山东口音，声音厚实有力，说话实在，爽朗，偶尔大嗓门。",
  "俺叫鲁红梅，济南人，五十二了。下巴这道小疤，是年轻时候在厂里干活碰的。俺这个人实在，说话直，干活快。演工人、演食堂大姐、演一个人撑起一个家的妈，俺心里有数。"),
 # ---------- East Asian men ----------
 ("002","邓小树","Deng Xiaoshu","贵州贵阳","Guiyang, Guizhou","又高又瘦，耳朵有点招风。","Tall, skinny, with ears that stick out a little.","zh",
  "22岁贵阳男生，普通话带一点西南口音，声音清亮、少年感，有点腼腆，说话时会笑。",
  "大家好，我叫邓小树，贵阳的，二十二岁。我妈说我长得跟树一样，又高又细，所以叫小树。我耳朵有点大，小时候老被笑，现在觉得挺好认的。我想演那种笨笨的、但特别真诚的男生。"),
 ("007","包满仓","Bao Mancang","天津","Tianjin","圆脸小眼，发际线往后跑，一张嘴就是相声。","Round face, small eyes, retreating hairline. Every sentence sounds like a punchline.","zh",
  "33岁天津男人，普通话带浓天津口音，声音明亮，贫嘴幽默，节奏感强，像说相声。",
  "嘿，各位好，我叫包满仓，天津卫的，三十三了。这名儿是我爷爷起的，说是粮仓满满不愁吃。您看我这脑门儿，越来越亮了，省电。我打小听相声长大，演个嘴贫的、演个老实人吃亏的，都行！"),
 ("012","雷大海","Lei Dahai","湖北武汉","Wuhan, Hubei","啤酒肚，寸头，笑起来震天响。","Beer belly, buzz cut and a laugh you can hear down the street.","zh",
  "46岁武汉男人，普通话带浓武汉口音，声音洪亮粗犷，豪爽，急脾气，但很热心。",
  "我叫雷大海，武汉的，四十六岁。你看我这个肚子，都是热干面跟啤酒喂出来的。我嗓门大，脾气急，但是心热。以前开过出租车，满武汉没有我不熟的路。演司机、演大排档老板，那是本色出演！"),
 ("017","顾文渊","Gu Wenyuan","上海","Shanghai","粗黑框眼镜，皱纹很深，灰发随手往后一拢。","Thick black glasses, deep lines and grey hair pushed back by hand.","zh",
  "60岁上海男性，普通话带上海口音，声音低沉温和，学者气，语速慢，用词讲究。",
  "我叫顾文渊，上海人，今年六十岁。在大学里教了三十年的书，教的是古典文学。退休以后，学生说我这张脸适合演戏，我就来试试。教授、老学者、固执的老父亲，这些角色我大概不用怎么演。"),
 ("022","秦烈","Qin Lie","陕西西安","Xi'an, Shaanxi","方下巴，浓眉，一身腱子肉。","Square jaw, heavy brows and solid muscle.","zh",
  "28岁西安男人，普通话带一点陕西口音，声音浑厚有力，说话简短干脆，有江湖气。",
  "我叫秦烈，西安人，二十八岁。练了十年散打，所以看着有点凶，其实我挺好说话的。动作戏是我的强项，打戏我自己上。我也想试试那种外表硬、心里软的角色，比如一个照顾妹妹的哥哥。"),
 ("027","朱有福","Zhu Youfu","广东佛山","Foshan, Guangdong","矮壮，头顶秃了，笑得比谁都开心。","Short and stocky, bald on top, always the happiest man in the room.","zh",
  "39岁佛山男人，普通话带粤语口音，声音明亮，乐呵呵，语速快，热情好客。",
  "哈喽大家好，我叫朱有福，佛山人，三十九岁。你看我这头，前面已经放假了，哈哈。我家开烧腊店的，从小在店里招呼客人，所以我最会讲好话。演老板、演开心果、演倒霉但乐观的人，没问题！"),
 ("032","葛长林","Ge Changlin","河北石家庄","Shijiazhuang, Hebei","马脸，眼袋重，一撇小胡子。","Long horse face, heavy eye bags and a neat mustache.","zh",
  "52岁石家庄男人，普通话带河北口音，声音低沉、慢、有点疲惫的幽默感，冷面笑匠。",
  "我叫葛长林，石家庄的，五十二。我这张脸长，眼袋重，大家说我天生一副没睡醒的样子。我以前是火车站的值班员，见惯了人来人往。我说话慢，但冷不丁一句能把人逗乐。演个冷面的老头，我在行。"),
 ("037","余福根","Yu Fugen","浙江宁波","Ningbo, Zhejiang","白发梳得整整齐齐，脸蛋圆圆的。","White hair combed neat, round rosy cheeks.","zh",
  "70岁宁波老爷爷，普通话带宁波口音，声音温和、慢、有点含糊的老人音，慈眉善目，爱讲古。",
  "我叫余福根，宁波人，七十岁了。年轻时候是跑船的，去过好多港口。现在呢，每天早上要喝一碗汤圆。我讲话慢，但故事多，你们要听，我能讲三天三夜。演爷爷、演老船长，我觉得蛮合适的。"),
 ("042","陆星野","Lu Xingye","广东深圳","Shenzhen, Guangdong","染了一头灰金色，嘴角总挂着一点坏笑。","Bleached ash-blond hair and a permanent half-smirk.","zh",
  "25岁深圳男生，普通话标准带一点港台腔，声音年轻、懒散、带点玩世不恭，语速随意。",
  "嗨，我是陆星野，深圳的，二十五岁。头发是上个月刚漂的，还行吧？我以前做过一段时间街舞，后来又去写代码，现在来演戏。我挺适合演那种看着吊儿郎当、其实什么都懂的年轻人。"),
 ("047","祁长风","Qi Changfeng","甘肃兰州","Lanzhou, Gansu","高瘦，脸颊凹，喉结很明显。","Tall and gaunt, hollow cheeks, a prominent Adam's apple.","zh",
  "42岁兰州男人，普通话带西北口音，声音干、低沉、有沙哑颗粒感，话少，沉默寡言。",
  "我叫祁长风，兰州人，四十二。话不多，见谅。在西北跑了十几年长途货车，一个人开夜路，习惯了安静。我觉得我适合演那种不说话的人，比如守夜的人、送信的人，或者一个藏着过去的男人。"),
 ("052","范一鸣","Fan Yiming","江苏无锡","Wuxi, Jiangsu","圆脸，侧分卷发，留着一小撮山羊胡。","Round face, side-parted waves and a neat little goatee.","zh",
  "36岁无锡男人，普通话带一点吴语口音，声音圆润，温和健谈，有点小得意，像社区活动的主持人。",
  "大家好，我是范一鸣，无锡人，三十六岁。以前在婚庆公司当过主持人，三百多场婚礼，台下的人哭我也跟着哭。这撮小胡子是我的标志。我适合演热心的主持人、爱面子的小老板，或者暖心的大哥。"),
 ("057","庞铁柱","Pang Tiezhu","河北唐山","Tangshan, Hebei","宽肩膀，一颗门牙有点歪，胡茬扎人。","Broad shoulders, one crooked front tooth, rough stubble.","zh",
  "57岁唐山男人，普通话带浓唐山口音，声音粗哑有劲，憨厚，说话带笑，接地气。",
  "我叫庞铁柱，唐山的，五十七了。名字土，人也实在。在钢厂干了三十年，力气大。我这颗门牙是年轻时候打球磕的，就不修了，留个纪念。演工人、演老实人、演倔老头，我都能演出那股劲儿。"),
 ("062","白云川","Bai Yunchuan","云南昆明","Kunming, Yunnan","眉心一颗痣，扎个小发髻，留点小胡子。","A mole between the brows, a small topknot and a thin goatee.","zh",
  "30岁昆明男人，普通话带一点云南口音，声音温和舒缓，带点慵懒和禅意，语速慢。",
  "你好，我叫白云川，昆明人，三十岁。我在大理开过一家小客栈，每天看云、煮茶、跟客人聊天。眉心这颗痣，好多人说像点上去的。我适合演那种看起来很佛系、其实心里很有故事的人。"),
 ("067","钟福海","Zhong Fuhai","广东广州","Guangzhou, Guangdong","脸蛋圆鼓鼓，笑眼，头发梳得想盖住头顶。","Big round cheeks, smiling eyes and a hopeful comb-over.","zh",
  "64岁广州阿伯，普通话带浓广东口音，声音和蔼、略沙，慢悠悠，爱开玩笑，像茶楼常客。",
  "大家好，我叫钟福海，广州人，六十四岁。每天早上一定要去饮早茶，一盅两件，跟老朋友吹吹水。我头顶的头发少了，所以要梳得靓一点。演阿伯、演茶楼老板、演好脾气的爷爷，交给我啦。"),
 ("072","尤嘉乐","You Jiale","广西南宁","Nanning, Guangxi","一边嘴角先笑，头发烫成小卷。","His smile starts on one side. Short permed curls.","zh",
  "24岁南宁男生，普通话带一点广西口音，声音明亮俏皮，爱开玩笑，语速快，阳光。",
  "嗨嗨，我是尤嘉乐，南宁的，二十四岁。我笑的时候只有一边嘴角动，朋友说我笑得很欠揍，哈哈。这个卷是我妈带我去烫的。我想演那种搞笑的室友、机灵的小跟班，或者一不小心成了主角的普通人。"),
 ("077","邵铁峰","Shao Tiefeng","黑龙江哈尔滨","Harbin, Heilongjiang","鼻梁有点歪，眉毛上一道小疤。","A slightly crooked nose and a small scar through one eyebrow.","zh",
  "48岁哈尔滨男人，普通话带东北口音，声音低沉粗糙，话不多，硬汉气，偶尔冷幽默。",
  "我叫邵铁峰，哈尔滨的，四十八。鼻子是年轻时候练拳歪的，眉毛这道疤是冬天摔的。看着凶，其实我挺爱养花的。我适合演警察、保安、老刑警，或者一个刀子嘴豆腐心的老哥。"),
 ("082","温书朗","Wen Shulang","广西桂林","Guilin, Guangxi","下巴有道深沟，头发微卷，笑起来很暖。","A deep cleft chin, loose waves and a warm smile.","zh",
  "35岁桂林男人，普通话标准，声音温暖醇厚，带磁性，语速舒缓，适合讲故事。",
  "你好，我是温书朗，桂林人，三十五岁。之前在电台做了几年夜间节目，陪很多睡不着的人聊天。我喜欢山水，也喜欢安静的爱情片。我想演一个好丈夫、一个温柔的老师，或者一个让人想信任的医生。"),
 ("087","杜守仁","Du Shouren","河南洛阳","Luoyang, Henan","白短发，瘦长脸，下巴一颗痣，眼睛总带笑。","Short white hair, a lean face, a mole on the chin and kind eyes.","zh",
  "72岁洛阳老人，普通话带河南口音，声音苍老但清晰，温和慈祥，语速慢，像老中医。",
  "我叫杜守仁，洛阳人，七十二了。家里三代都是开中药铺的，我从小闻着药香长大。说话慢，你们莫嫌弃。我适合演老大夫、老先生，或者在关键时候点醒年轻人的那个老人。"),
 ("092","申大力","Shen Dali","河北保定","Baoding, Hebei","脖子粗，平头，嘴角一翘就是不服。","Thick neck, flat-top haircut and a 'try me' smirk.","zh",
  "41岁保定男人，普通话带河北口音，声音粗壮，自信带点痞气，语速中等，爱抬杠。",
  "我叫申大力，保定人，四十一。名字叫大力，人也真有力气，以前在驾校当教练，骂人一套一套的，学员都怕我。我这人爱抬杠，但讲义气。演教练、演小头目、演嘴硬的大哥，我在行。"),
 ("097","涂乐天","Tu Letian","湖北宜昌","Yichang, Hubei","脸有点肉，耳朵大，永远一副没睡醒的笑。","Chubby cheeks, big ears and a sleepy, easy grin.","zh",
  "29岁宜昌男生，普通话带一点湖北口音，声音慵懒松弛，慢吞吞，爱打哈哈，很治愈。",
  "大家好……我叫涂乐天，宜昌人，二十九岁。名字叫乐天，人也比较乐天，天塌下来先睡一觉再说。我说话慢，别着急哈。我觉得我很适合演那种懒洋洋的室友，或者关键时刻突然很靠谱的人。"),
 # ---------- White women ----------
 ("003","克拉拉·沃斯","Clara Vos","荷兰鹿特丹","Rotterdam, Netherlands","高鼻梁，门牙有缝，笑得毫无保留。","Long nose, gap-toothed and laughs without holding back.","en",
  "25岁荷兰女孩，说英语带轻微荷兰口音，声音明亮、直率、有活力，语速稍快，爱笑。",
  "Hi! I'm Clara Vos, I'm twenty-five, and I'm from Rotterdam. Yes, there's a gap in my teeth, and no, I'm not fixing it. I grew up on a bike, in the rain, arguing with my brothers. Give me the friend who says the thing everyone else is thinking."),
 ("008","英格丽·哈尔沃森","Ingrid Halvorsen","挪威卑尔根","Bergen, Norway","高，下颌方，眉毛淡得几乎看不见。","Tall, square-jawed, with brows so pale they almost vanish.","en",
  "34岁挪威女性，说英语带挪威口音，声音沉稳、冷静、清晰，语速慢，干练的幽默。",
  "Hello. I'm Ingrid Halvorsen, thirty-four, from Bergen in Norway. It rains there about three hundred days a year, so I'm very patient. I used to guide hikers up mountains. I'd love to play a ship captain, a detective, or the calm one when everything falls apart."),
 ("013","玛姬·多伊尔","Maggie Doyle","爱尔兰科克","Cork, Ireland","红扑扑的圆脸，笑纹深，短发。","Rosy round face, deep laugh lines, short pixie cut.","en",
  "47岁爱尔兰女性，说英语带浓爱尔兰口音，声音温暖、爽朗、爱说笑，语速快。",
  "Well hello there, I'm Maggie Doyle, forty-seven, from Cork. I ran a pub for twelve years, so there's no story I haven't heard twice. I laugh loud and I talk fast, sorry about that. Cast me as the landlady, the nosy aunt, or the mum who knows everything."),
 ("018","埃莱娜·马尔尚","Hélène Marchand","法国里昂","Lyon, France","鹰钩鼻，薄唇，银发侧分，细框眼镜。","Aquiline nose, thin lips, silver side-parted hair and fine glasses.","en",
  "63岁法国女性，说英语带法国口音，声音优雅、略低、清晰，语气克制而犀利。",
  "Good afternoon. I am Hélène Marchand. I am sixty-three, and I come from Lyon. For thirty years I taught piano to children who did not want to practise. I am strict, yes, but fair. I would make a very good headmistress, or a grandmother with secrets."),
 ("023","杰玛·孔蒂","Gemma Conti","意大利那不勒斯","Naples, Italy","眼睛大，嘴巴宽，卷发高高扎起。","Big eyes, a wide mouth and dark curls piled up high.","en",
  "22岁意大利女孩，说英语带意大利口音，声音热情、明亮、表情丰富，说话手舞足蹈的感觉，语速快。",
  "Ciao! I'm Gemma Conti, twenty-two, from Naples. My family says I talk with my hands, my face, my whole body, and they're right. I grew up above my nonna's bakery. I want to play someone loud, warm, a little dramatic, and always the first one to cry at weddings."),
 ("028","露西娅·奥尔特加","Lucía Ortega","西班牙塞维利亚","Seville, Spain","橄榄色皮肤，浓眉，高鼻梁，长卷发。","Olive skin, thick brows, a strong nose and long dark waves.","en",
  "39岁西班牙女性，说英语带西班牙口音，声音浓郁、温暖、有力量，语速中等，富有激情。",
  "Hola, I'm Lucía Ortega, I'm thirty-nine, from Seville. I danced flamenco for many years, so I know how to make an entrance. I'm passionate, I'm stubborn, and I will feed you whether you're hungry or not. Give me a mother, a matriarch, or a woman with fire."),
 ("033","布伦达·科瓦尔斯基","Brenda Kowalski","美国密尔沃基","Milwaukee, USA","双下巴，小眼睛，一头金灰色小卷。","Soft double chin, small eyes and short blonde-grey curls.","en",
  "56岁美国中西部女性，说英语带美国中西部口音，声音亲切、热心、有点碎嘴，语速中等。",
  "Hi there, I'm Brenda Kowalski, fifty-six, from Milwaukee, Wisconsin. I've worked the front desk at the same dentist's office for twenty-two years, so I know everybody's business. I bake for every occasion. Cast me as the neighbor, the school secretary, the lady with the casserole."),
 ("038","伊迪丝·彭伯顿","Edith Pemberton","英国巴斯","Bath, England","脸颊粉粉的，白发松松盘着，总在笑。","Pink cheeks, a loose white bun and a smile that never quits.","en",
  "72岁英国老太太，说英式英语，声音轻柔、慈祥、略颤但清晰，语速慢，优雅可爱。",
  "Hello, dear. I'm Edith Pemberton, I'm seventy-two, and I live in Bath. I've kept bees, raised three children, and won a village baking contest, twice. I'm rather new to acting, but I've been watching people my whole life. A grandmother, a librarian, a sweet old lady who isn't."),
 ("043","萨莎·克尔","Sasha Kerr","英国格拉斯哥","Glasgow, Scotland","颧骨锋利，脸长，头发剃得很短。","Razor-sharp cheekbones, a long face and a buzzed head.","en",
  "29岁苏格兰女性，说英语带苏格兰口音，声音低、利落、带点冷幽默和叛逆，语速中等。",
  "Hiya, I'm Sasha Kerr, twenty-nine, from Glasgow. I shaved my head at nineteen and never looked back. I've been a bike courier, a bartender, and a drummer in a very bad band. I'd love to play the rebel, the soldier, or the woman who doesn't need saving."),
 ("048","波琳娜·奥尔洛娃","Polina Orlova","俄罗斯圣彼得堡","Saint Petersburg, Russia","颧骨宽，浅色眼睛分得开，直发。","Wide cheekbones, pale wide-set eyes and straight light-brown hair.","en",
  "43岁俄罗斯女性，说英语带俄语口音，声音清冷、低沉、有分量，语速慢，带一点忧郁。",
  "Hello. My name is Polina Orlova. I am forty-three, from Saint Petersburg. I worked many years as a translator, so I like words very much, and silence even more. I think I could play a spy, a scientist, or a mother who carries a long and heavy story."),
 ("053","黛西·惠特洛克","Daisy Whitlock","英国利兹","Leeds, England","圆脸酒窝，栗色齐刘海短发。","Round face, dimples and a chestnut bob with bangs.","en",
  "31岁英格兰北部女性，说英语带约克郡口音，声音甜、俏皮、爱笑，语速快。",
  "Hiya! I'm Daisy Whitlock, thirty-one, from Leeds. I work in a cake shop, which explains a lot, honestly. People tell me I'm the kind of person you'd tell a secret to on a bus. I'd love to play the best friend, the clumsy one, the one who falls in love too fast."),
 ("058","米丽娅姆·阿德勒","Miriam Adler","奥地利维也纳","Vienna, Austria","高瘦，鹰钩鼻，眼窝深，深色头发盘起。","Tall and slim, a hooked nose, deep-set eyes and dark hair pinned up.","en",
  "50岁奥地利女性，说英语带德语口音，声音低沉、优雅、略带讽刺，语速稳定，很有气场。",
  "Good evening. I am Miriam Adler, fifty, from Vienna. I spent twenty years backstage at the opera, so I know drama very well. People say I look severe. That is mostly true. I would be wonderful as a duchess, a museum director, or a villain with excellent taste."),
 ("063","安妮卡·勃兰特","Annika Brandt","德国汉堡","Hamburg, Germany","淡淡的雀斑，翘鼻子，毛躁的深金色发髻。","Light freckles, an upturned nose and a frizzy dark-blonde bun.","en",
  "26岁德国女孩，说英语带轻微德国口音，声音清脆、认真、有点书呆子的可爱，语速中等。",
  "Hi, I'm Annika Brandt, twenty-six, from Hamburg. I study marine biology, so if you need someone to talk about octopuses for an hour, I'm here. My hair does whatever it wants. I'd like to play the nerdy one, the scientist, or the girl who finds the clue nobody saw."),
 ("068","多特·哈林顿","Dot Harrington","澳大利亚墨尔本","Melbourne, Australia","方脸，厚镜片，灰短发，说话不绕弯。","Square face, thick glasses, cropped grey hair. No small talk.","en",
  "59岁澳大利亚女性，说英语带澳洲口音，声音粗哑、直爽、带点粗糙的幽默，语速中等偏快。",
  "G'day, I'm Dot Harrington. Fifty-nine, from Melbourne. I drove school buses for thirty years, so trust me, nothing scares me anymore. I say what I mean and I mean what I say. Put me in as the tough coach, the bossy aunt, or the woman who runs the whole town."),
 ("073","阿涅丝·勒费弗尔","Agnès Lefèvre","法国巴黎","Paris, France","尖下巴，耳朵有点大，利落的深色波波头。","Pointed chin, slightly big ears and a sleek dark bob.","en",
  "37岁法国女性，说英语带法国口音，声音轻快、俏皮、带点慵懒，语速中等。",
  "Bonjour, I am Agnès Lefèvre, thirty-seven, from Paris. I sell old books by the river, and I read most of them before I sell them. My ears are a bit big, I know, they make me a very good listener. I would love to play a writer, a thief, or a woman in a comedy."),
 ("078","罗斯玛丽·芬奇","Rosemary Finch","英国卡迪夫","Cardiff, Wales","脸颊圆润，鼻头红红，一头蓬松白卷发。","Soft jowls, a rosy nose and a cloud of curly white hair.","en",
  "67岁威尔士女性，说英语带威尔士口音，声音温暖、歌唱般的语调起伏，语速中等，慈爱。",
  "Hello, love! I'm Rosemary Finch, sixty-seven, from Cardiff. I sang in a choir for forty years, so I can't help putting a bit of a tune in everything I say. I've got five grandchildren and a very fat cat. Cast me as the nan, the choir lady, the kind soul next door."),
 ("083","基娅拉·贝内代蒂","Chiara Benedetti","意大利博洛尼亚","Bologna, Italy","浓眉，鼻梁微歪，栗色波浪长发。","Strong brows, a slightly crooked nose and wavy chestnut hair.","en",
  "23岁意大利女孩，说英语带意大利口音，声音温柔、真诚、带点倔强，语速中等。",
  "Hi, I'm Chiara Benedetti, twenty-three, from Bologna. I broke my nose playing football when I was twelve, and I scored anyway. I study architecture and I draw everything I see. I would love to play a young artist, a stubborn daughter, or someone falling in love in a new city."),
 ("088","苔丝·卡拉汉","Tess Callahan","美国圣迭戈","San Diego, USA","晒得黝黑，眼角笑纹，沙金色马尾。","Sun-tanned, crow's feet and a sandy-blonde ponytail.","en",
  "45岁美国西海岸女性，说美式英语，声音明亮、松弛、阳光，语速中等，有运动员的爽快。",
  "Hey! I'm Tess Callahan, forty-five, from San Diego. I've taught surfing for twenty years, so I've got the tan and the wrinkles to prove it. I'm calm in big waves and terrible at sitting still. I'd love to play a coach, a lifeguard, or a mom who still skates to work."),
 ("093","薇拉·库切罗娃","Vera Kučerová","捷克布拉格","Prague, Czech Republic","长脸，眼皮沉沉的，黑色及下巴卷发。","Long face, heavy-lidded eyes and black chin-length waves.","en",
  "53岁捷克女性，说英语带中欧口音，声音低沉、慵懒、带点神秘和讽刺，语速慢。",
  "Hello. I am Vera Kučerová, fifty-three, from Prague. I read tarot cards in a café for many years, mostly for tourists, sometimes for myself. People say I look like I know something. Maybe I do. I would play a fortune teller, a landlady, or the mother in a strange old house."),
 ("098","芙蕾雅·莫滕森","Freja Mortensen","丹麦奥胡斯","Aarhus, Denmark","高大骨架宽，圆脸，金色短寸。","Tall, big-boned, round-faced, with a short blonde undercut.","en",
  "30岁丹麦女性，说英语带丹麦口音，声音洪亮、开朗、直率，语速中等，很有力量感。",
  "Hej! I'm Freja Mortensen, thirty, from Aarhus in Denmark. I played handball for the national youth team, so I'm strong, loud, and very competitive at board games. I'd love to play a firefighter, a Viking, or the friend who carries everyone home after a party."),
 # ---------- White men ----------
 ("004","费利克斯·哈特曼","Felix Hartmann","德国莱比锡","Leipzig, Germany","鼻子大，脸窄，一头浅棕卷发。","Big nose, narrow face and a mop of light-brown curls.","en",
  "24岁德国男生，说英语带德国口音，声音偏高、紧张、有点笨拙的可爱，语速时快时慢。",
  "Hello, I'm Felix Hartmann. I'm twenty-four, from Leipzig. I play the cello, badly, and I collect old maps, very well. I get nervous when people look at me, which is funny for an actor, I know. I'd like to play the awkward genius, the shy boyfriend, or the boy who gets lost."),
 ("009","卡勒姆·里德","Callum Reid","英国阿伯丁","Aberdeen, Scotland","光头，大胡子，熊一样的块头。","Shaved head, big bushy beard and the build of a bear.","en",
  "35岁苏格兰男人，说英语带浓苏格兰口音，声音浑厚低沉，粗犷但温和，语速中等。",
  "Alright, I'm Callum Reid, thirty-five, from Aberdeen. I worked on the oil rigs out in the North Sea for ten years, so I'm used to wind, noise, and very bad coffee. I look scary, but I cry at dog films. Give me a bodyguard, a blacksmith, or a big soft giant."),
 ("014","雷·科瓦尔奇克","Ray Kowalczyk","美国匹兹堡","Pittsburgh, USA","啤酒肚，发际线后退，一大撇胡子。","Pot belly, receding hairline and a big thick mustache.","en",
  "48岁美国男人，说英语带匹兹堡口音，声音粗哑、热络、爱抱怨，语速中等偏快，蓝领幽默。",
  "Hey, how ya doin'. Ray Kowalczyk, forty-eight, Pittsburgh born and raised. I've run a hardware store on the same corner for twenty-five years. I complain about everything and fix anything. Cast me as the plumber, the coach, the dad who swears at the TV during the game."),
 ("019","安布罗斯·莱西","Ambrose Lacey","英国爱丁堡","Edinburgh, Scotland","高瘦，白发及领，眉毛又浓又乱。","Tall and thin, white hair to the collar and wild bushy brows.","en",
  "66岁苏格兰老绅士，说英语带爱丁堡口音，声音深沉、缓慢、带戏剧腔，像老派舞台演员。",
  "Good day. Ambrose Lacey, sixty-six years old, from Edinburgh. I spent forty years in the theatre, mostly playing kings, ghosts, and very angry fathers. My eyebrows have a life of their own. I would be delighted to play a wizard, a professor, or a ghost who won't leave."),
 ("024","尼科斯·安德鲁","Nikos Andreou","希腊塞萨洛尼基","Thessaloniki, Greece","浓密黑卷发，两道眉毛快连在一起，高鼻梁。","Thick black curls, brows that nearly meet and a strong nose.","en",
  "28岁希腊男人，说英语带希腊口音，声音热情、温暖、爱说笑，语速快，很有感染力。",
  "Yassou! I'm Nikos Andreou, twenty-eight, from Thessaloniki. My family runs a fish taverna by the sea, and I've been carrying plates since I was eight. I sing, I dance, I talk too much. Give me the charming waiter, the romantic fool, or the cousin who ruins the wedding."),
 ("029","汤米·布兰尼根","Tommy Brannigan","英国利物浦","Liverpool, England","矮壮，方脑袋，鼻子被打扁过。","Short and stocky, square head, a nose flattened in the ring.","en",
  "41岁利物浦男人，说英语带浓利物浦口音，声音粗犷、直爽、幽默，语速快，有拳击手的劲儿。",
  "Alright, I'm Tommy Brannigan, forty-one, from Liverpool. I boxed for fifteen years, hence the nose. Now I run a gym for kids who need somewhere to go after school. I'm tougher on the outside than the inside. Cast me as the trainer, the bouncer, or the dad who never gives up."),
 ("034","帕维尔·索科洛夫","Pavel Sokolov","俄罗斯新西伯利亚","Novosibirsk, Russia","颧骨宽，深陷的蓝眼睛，花白短胡子。","Broad cheekbones, deep-set blue eyes and a salt-and-pepper beard.","en",
  "55岁俄罗斯男人，说英语带浓俄语口音，声音低沉粗厚，沉稳，话少，有分量。",
  "Hello. Pavel Sokolov. Fifty-five, from Novosibirsk, in Siberia. I drove trains across the taiga for thirty years. Very long trips, very little talking. I like chess, black bread, and quiet people. I think I could play a soldier, a ship engineer, or a father who never says I love you."),
 ("039","亨利·杜布瓦","Henri Dubois","法国波尔多","Bordeaux, France","长脸，鹰钩鼻，秃顶一圈白发，金属细框眼镜。","Long face, hooked nose, a white fringe round a bald crown, wire glasses.","en",
  "73岁法国老先生，说英语带法国口音，声音苍老、细腻、慢条斯理，带点挑剔和幽默。",
  "Bonjour. I am Henri Dubois, seventy-three, from Bordeaux. I made wine for fifty years, and I am still not satisfied with any of it. My grandchildren say I am impossible to please. They are correct. I would play a grumpy grandfather, a strict teacher, or a very old detective."),
 ("044","卢卡斯·贝格尔","Lukas Berger","奥地利因斯布鲁克","Innsbruck, Austria","高瘦，长下巴，金发软塌塌，总像刚睡醒。","Lanky, long-chinned, floppy blond hair and permanently sleepy eyes.","en",
  "22岁奥地利男生，说英语带德语口音，声音慵懒、慢、温柔，有点迷糊，语速慢。",
  "Hi... I'm Lukas Berger, twenty-two, from Innsbruck. I teach snowboarding in winter and sleep most of the summer. People think I'm always tired. I'm not, I'm just relaxed. I'd like to play the dreamy younger brother, the stoner roommate, or the boy who's secretly brave."),
 ("049","欧文·普赖斯","Owen Pryce","英国斯旺西","Swansea, Wales","圆脸，短胡子，波浪长发披到肩。","Round face, short beard and wavy hair down to the shoulders.","en",
  "38岁威尔士男人，说英语带威尔士口音，声音温厚、歌唱般的抑扬，开朗，语速中等。",
  "Hiya, I'm Owen Pryce, thirty-eight, from Swansea in Wales. I teach guitar, I sing in a pub on Fridays, and I make a very serious Sunday roast. People say I give big hugs. I'd love to play the folk singer, the gentle dad, or the friend who always shows up with food."),
 ("054","伯努瓦·拉克鲁瓦","Benoît Lacroix","法国马赛","Marseille, France","耳朵大，一字小胡子，头发侧分抹得服帖。","Big ears, a thin pencil mustache and hair parted just so.","en",
  "31岁法国男人，说英语带法国南部口音，声音轻快、自负又滑稽，语速快，戏剧化。",
  "Bonjour! I am Benoît Lacroix, thirty-one, from Marseille. I am a waiter in a very fancy restaurant, and I take it very, very seriously. This mustache took me three years. I would be perfect as a snobbish maître d', a ridiculous count, or a man who thinks he's smarter than he is."),
 ("059","汉克·索伦森","Hank Sorensen","美国明尼苏达","Minnesota, USA","宽肩，风霜脸，灰色平头，脸上一道疤。","Broad shoulders, a weathered face, a grey crew cut and a scar.","en",
  "60岁美国男人，说英语带明尼苏达口音，声音低沉、慢、稳，话少，可靠的老派硬汉。",
  "Name's Hank Sorensen. Sixty years old, from northern Minnesota. Spent most of my life on the lake, fishing, and fixing boats. Got this scar from a bad winter, long story. I don't talk much, but I listen. I'd play a sheriff, a fisherman, or a grandfather with a good secret."),
 ("064","卡斯珀·霍尔姆","Kasper Holm","丹麦哥本哈根","Copenhagen, Denmark","块头大，方下巴，金色卷发，胡茬。","Big and broad, square-jawed, curly blond hair and stubble.","en",
  "26岁丹麦男生，说英语带丹麦口音，声音憨厚、开朗、有点傻乐，语速中等。",
  "Hej, I'm Kasper Holm, twenty-six, from Copenhagen. I'm a baker. I start work at four in the morning, so if I look sleepy, that's why. I'm big, but I'm very gentle, ask anyone. I'd like to play the lovable giant, the loyal best friend, or the guy who's terrible at flirting."),
 ("069","埃德蒙·克兰","Edmund Crane","美国波士顿","Boston, USA","又高又瘦，鹰钩鼻，发际线往后退。","Very tall, very thin, a hawk nose and a receding hairline.","en",
  "44岁美国男人，说英语带波士顿口音，声音细长、紧绷、神经质的幽默，语速快。",
  "Hi, uh, Edmund Crane. Forty-four. Boston. I'm an accountant, I was an accountant, I'm trying something new, okay? I'm six foot three and I bump my head on everything. People say I look like I'm worried. I usually am. Cast me as the nervous lawyer, the butler, or the man who panics."),
 ("074","布鲁诺·费拉罗","Bruno Ferraro","意大利都灵","Turin, Italy","下巴肉多，灰色大胡子，头顶光亮。","Jowly, a bushy grey mustache and a shiny bald top.","en",
  "52岁意大利男人，说英语带意大利口音，声音浑厚、热情、爱抱怨又爱笑，语速快，手势感强。",
  "Buongiorno! Bruno Ferraro, fifty-two, from Turin. I fix old Fiat cars, and I talk to them like they are my children. Sometimes they listen. My mustache is famous in my neighborhood. I would be perfect as a mechanic, a big uncle, or the restaurant owner who shouts and then hugs you."),
 ("079","德克兰·肖","Declan Shaw","爱尔兰都柏林","Dublin, Ireland","方下巴，下巴有沟，笑起来歪歪的。","Square jaw, a cleft chin and a crooked, charming smile.","en",
  "33岁爱尔兰男人，说英语带都柏林口音，声音迷人、轻松、带点调皮，语速中等。",
  "How's it going, I'm Declan Shaw, thirty-three, from Dublin. I played rugby until my knee said no, and now I coach the under-twelves. My smile goes a bit sideways, my mam says it's how you know I'm lying. I'd love to play the charmer, the firefighter, or the guy next door."),
 ("084","格斯·阿伯内西","Gus Abernathy","美国奥斯汀","Austin, USA","圆脸刮得干净，灰色长马尾，笑纹很深。","Clean-shaven round face, a long grey ponytail and deep smile lines.","en",
  "69岁美国得州男人，说英语带美国南方口音，声音沙哑、悠闲、慢吞吞，很有故事感。",
  "Well howdy, I'm Gus Abernathy. Sixty-nine, from Austin, Texas. I've been playing bass in bars since before most folks were born. Never cut the ponytail, never will. I tell long stories and I don't apologize for it. Cast me as the old rocker, the hippie grandpa, or the wise man at the bar."),
 ("089","米洛·科瓦奇","Milo Kovač","克罗地亚萨格勒布","Zagreb, Croatia","矮小精瘦，窄脸，眼睛亮，黑发乱糟糟。","Short and wiry, a narrow face, bright eyes and messy black hair.","en",
  "37岁克罗地亚男人，说英语带东欧口音，声音机灵、跳脱、语速很快，有点神经质的喜感。",
  "Hi, hi, Milo Kovač, thirty-seven, from Zagreb. I'm a street magician, so if your watch is missing, that's not me. Probably. I'm small and fast and I never sit still. I'd love to play a pickpocket, a wedding planner, or the friend with a terrible plan that somehow works."),
 # ---------- Black women ----------
 ("005","阿玛·门萨","Ama Mensah","加纳阿克拉","Accra, Ghana","蓬蓬的爆炸头，门牙有缝，眼睛特别亮。","An afro puff, a gap-toothed grin and very bright eyes.","en",
  "24岁加纳女孩，说英语带加纳口音，声音明亮、活泼、爱笑，语速快，元气满满。",
  "Hi, I'm Ama Mensah, twenty-four, from Accra in Ghana. I sell fabric at the market with my aunties, so I can talk to anybody about anything. I laugh at my own jokes, it's a problem. I'd love to play the funny best friend, the young entrepreneur, or a girl with big dreams."),
 ("015","福拉克·阿德耶米","Folake Adeyemi","尼日利亚拉各斯","Lagos, Nigeria","颧骨高，眉毛浓，头发剪得很短。","High cheekbones, strong brows and close-cropped natural hair.","en",
  "38岁尼日利亚女性，说英语带尼日利亚口音，声音浑厚、自信、干练，语速中等，有掌控感。",
  "Good afternoon, I'm Folake Adeyemi, thirty-eight, from Lagos. I run my own event company, which means I am always calm and always in control, even when I'm not. I love a strong woman on screen. Give me a CEO, a lawyer, or a mother who will fight the whole world for her children."),
 ("025","伯妮丝·华盛顿","Bernice Washington","美国亚特兰大","Atlanta, USA","圆脸，脸颊饱满，灰色小辫子。","Round full cheeks and short grey-streaked twists.","en",
  "55岁美国南方女性，说美式英语带南方口音，声音温暖醇厚、慈爱、有教堂唱诗班的韵味，语速中等。",
  "Hey baby, I'm Bernice Washington, fifty-five, from Atlanta, Georgia. I've led the church choir for twenty years, and I run the best soul food kitchen on my street. I hug everybody, so get ready. Cast me as the mama, the auntie, or the lady who tells you the truth when you need it."),
 ("035","扎瓦迪·姆旺吉","Zawadi Mwangi","肯尼亚内罗毕","Nairobi, Kenya","高个子，光头，下颌线锋利，眼睛很大。","Tall, shaved head, a sharp jaw and big expressive eyes.","en",
  "29岁肯尼亚女性，说英语带东非口音，声音清亮、坚定、有力量，语速中等，自信。",
  "Hello, I'm Zawadi Mwangi, twenty-nine, from Nairobi in Kenya. I ran the eight hundred metres for my country, so I know how to keep going when it hurts. I shaved my head before a race once and kept it. I'd love to play an athlete, a pilot, or a warrior in a story people remember."),
 ("045","海辛丝·坎贝尔","Hyacinth Campbell","牙买加金斯敦","Kingston, Jamaica","银色短卷发，圆框眼镜，笑纹深深。","Short silver curls, round glasses and deep smile lines.","en",
  "66岁牙买加女性，说英语带牙买加口音，声音温暖、有韵律、慈祥又俏皮，语速中等。",
  "Hello darling, I'm Hyacinth Campbell, sixty-six, from Kingston, Jamaica. I was a nurse for forty years, so I've seen everything, and I'm not shy about telling you to eat your vegetables. I love dominoes and loud music. Cast me as the grandma, the nurse, or the neighbour who adopts everyone."),
 ("055","艾莎图·迪亚洛","Aïssatou Diallo","塞内加尔达喀尔","Dakar, Senegal","酒窝很深，嘴唇上方一颗痣，长辫子束在脑后。","Deep dimples, a mole above her lip and long braids tied back.","en",
  "33岁塞内加尔女性，说英语带法语和西非口音，声音柔和、温暖、优雅，语速中等。",
  "Hello, I'm Aïssatou Diallo, thirty-three, from Dakar in Senegal. I speak French, Wolof, and English, and I mix them all when I'm excited. I design clothes, and I braid my sister's hair every Sunday. I'd love to play a designer, a teacher, or a woman starting her life again."),
 ("065","克洛黛特·莫雷尔","Claudette Morel","法国巴黎","Paris, France","高个子，长脸，颧骨高，利落的直发波波头。","Tall, long-faced, high cheekbones and a sleek relaxed bob.","en",
  "47岁法国女性，说英语带法国口音，声音低沉、优雅、从容，语速慢，有权威感。",
  "Good evening. My name is Claudette Morel. I am forty-seven, and I live in Paris. For many years I was a news editor, so I am very good at deciding what matters. I am calm, and I am rarely wrong. I would play a judge, a diplomat, or a mother who knows the whole story."),
 ("075","贾丝敏·霍洛韦","Jasmine Holloway","英国伦敦","London, England","个子小，心形脸，及肩卷发。","Petite, heart-shaped face and shoulder-length curls.","en",
  "25岁伦敦女孩，说英语带伦敦口音，声音轻快、自信、带点俏皮，语速快。",
  "Hiya, I'm Jasmine Holloway, twenty-five, from South London. I'm a hairdresser, so I know everyone's gossip before they do. I'm small, but trust me, I'm the loudest person at the party. I'd love to play the cheeky best friend, the girl with a plan, or the boss of the whole crew."),
 ("085","坦迪薇·德拉米尼","Thandiwe Dlamini","南非约翰内斯堡","Johannesburg, South Africa","下巴方，笑纹深，椒盐色短爆炸头。","Square jaw, deep laugh lines and a short salt-and-pepper afro.","en",
  "59岁南非女性，说英语带南非口音，声音浑厚、温暖、有力量，说话带笑，语速中等。",
  "Sawubona, hello! I'm Thandiwe Dlamini, fifty-nine, from Johannesburg. I was a school principal for twenty-five years, so I can quiet a room with one look. But I laugh easily, I promise. I'd love to play a principal, a grandmother, or a woman who leads her whole community."),
 # ---------- Black men ----------
 ("010","亚乌·奥乌苏","Yaw Owusu","加纳库马西","Kumasi, Ghana","长脸，大耳朵，短短的小辫子。","Long face, big ears and short twists.","en",
  "26岁加纳男生，说英语带加纳口音，声音温和、开朗、带点害羞，语速中等。",
  "Hello, I'm Yaw Owusu, twenty-six, from Kumasi in Ghana. I'm an engineer, but on weekends I play drums at weddings. My ears are big, my mother says it's because I listen well. I'd like to play the kind young man, the inventor, or the guy who's quietly in love with his neighbour."),
 ("020","德莱·阿贾伊","Dele Ajayi","尼日利亚拉各斯","Lagos, Nigeria","光头，浓黑大胡子，浓眉，块头大。","Bald head, a full black beard, thick brows and a big frame.","en",
  "40岁尼日利亚男人，说英语带尼日利亚口音，声音低沉浑厚、有威严，又带幽默感，语速中等。",
  "Good day, I'm Dele Ajayi, forty, from Lagos, Nigeria. I own a car repair workshop, and my voice can stop an argument from across the street. I look serious, but I'm the funniest man in my family, ask them. Cast me as the big boss, the bodyguard, or the uncle everybody fears and loves."),
 ("030","克拉伦斯·佩蒂福德","Clarence Pettiford","美国孟菲斯","Memphis, USA","圆脸，啤酒肚，灰白小胡子。","Round face, a round belly and a grey mustache.","en",
  "53岁美国南方男人，说美式英语带孟菲斯口音，声音醇厚、慢悠悠、爱讲笑话，语速慢。",
  "Hey now, I'm Clarence Pettiford, fifty-three, from Memphis, Tennessee. I've run a barbecue joint for twenty years, and my ribs have fans in three states. I like the blues, long naps, and longer stories. Cast me as the diner owner, the deacon, or the old friend with all the answers."),
 ("040","贾伦·布鲁克斯","Jalen Brooks","美国芝加哥","Chicago, USA","高顶短发，修得整齐的短胡子，眼神沉稳。","A high-top fade, a neat short beard and a calm, steady look.","en",
  "31岁芝加哥男人，说美式英语，声音沉稳、温和、自信，语速中等，很有说服力。",
  "Hey, I'm Jalen Brooks, thirty-one, from Chicago's South Side. I'm a high school basketball coach and part-time DJ. I stay calm when everyone else is losing it, that's kind of my thing. I'd love to play a coach, a detective, or the brother who holds the family together."),
 ("050","乌斯曼·库利巴利","Ousmane Coulibaly","马里巴马科","Bamako, Mali","光头，白色短胡子，额头皱纹深，细框眼镜。","Bald, a short white beard, a lined forehead and thin glasses.","en",
  "68岁马里老人，说英语带法语和西非口音，声音苍老、平静、充满智慧，语速慢。",
  "Peace be with you. I am Ousmane Coulibaly, sixty-eight, from Bamako in Mali. I taught history at the university for many years, and I still believe a good story can change a person. I speak slowly, please be patient. I would play a teacher, an elder, or a grandfather with wisdom."),
 ("060","奇迪·埃泽","Chidi Eze","尼日利亚埃努古","Enugu, Nigeria","圆脸，酒窝深，短寸头，敦实。","Round face, deep dimples, a buzz cut and a sturdy build.","en",
  "23岁尼日利亚男生，说英语带尼日利亚口音，声音年轻、开心、爱笑，语速快，阳光。",
  "Hey hey! I'm Chidi Eze, twenty-three, from Enugu in Nigeria. I study computer science, but honestly I spend more time making comedy videos. People say my dimples are dangerous. I'd love to play the funny little brother, the hopeless romantic, or the student who accidentally saves the day."),
 ("070","易卜拉希马·恩迪亚耶","Ibrahima Ndiaye","塞内加尔达喀尔","Dakar, Senegal","高瘦，颧骨锋利，光头，一字小胡子。","Tall and slim, sharp cheekbones, a shaved head and a thin mustache.","en",
  "45岁塞内加尔男人，说英语带法语口音，声音低沉、优雅、从容，语速慢，很有风度。",
  "Good evening. I am Ibrahima Ndiaye, forty-five, from Dakar, Senegal. I was a jazz saxophonist in Paris for fifteen years before I came home. I like good suits and quiet rooms. I would be a fine diplomat, a mysterious stranger, or a man who walks in and changes everything."),
 ("080","德斯蒙德·埃勒里","Desmond Ellery","英国伯明翰","Birmingham, England","脸蛋肉肉的，脖子粗，短脏辫。","Chubby cheeks, a thick neck and short locs.","en",
  "36岁英国伯明翰男人，说英语带伯明翰口音，声音憨厚、松弛、幽默，语速中等。",
  "Alright, I'm Desmond Ellery, thirty-six, from Birmingham. I drive the number fifty bus, and I know every regular by name and by sandwich. I'm a big lad and a big softie. I'd love to play the bus driver, the best mate, or the dad who's trying his best, bless him."),
 ("090","塞缪尔·奥杜亚","Samuel Oduya","肯尼亚基苏木","Kisumu, Kenya","眼窝深，椒盐色胡子，灰色短爆炸头。","Deep-set eyes, a salt-and-pepper beard and a short grey afro.","en",
  "58岁肯尼亚男人，说英语带东非口音，声音温和、沉稳、醇厚，语速慢，像个讲故事的人。",
  "Hello, my friends. I'm Samuel Oduya, fifty-eight, from Kisumu by Lake Victoria. I've been a fisherman, a radio host, and now an actor. I like to take my time, with stories and with people. I'd love to play a wise father, a village chief, or an old man who remembers everything."),
]

def slugify(name):
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()
    return s

idx = {x["id"]: x for x in json.load(open(os.path.join(HERE, "..", "library", "claude-casting-2026-10-07", "index.json")))}
out, seen = [], set()
for cc, zh, en, oz, oe, tz, te, lang, brief, line in R:
    src = idx[f"CC-{cc}"]["description"]
    m = re.search(r"about (\d+), .*?about (\d+) cm", src)
    gender = "female" if re.search(r"\bwoman\b", src) else "male"
    group = "east-asian" if src.startswith("East Asian") else "black" if src.startswith("Black") else "white"
    slug = slugify(en)
    assert slug not in seen, slug
    seen.add(slug)
    out.append({
        "slug": slug, "source": f"CC-{cc}", "nameZh": zh, "nameEn": en, "gender": gender, "group": group,
        "age": int(m.group(1)), "heightCm": int(m.group(2)),
        "origin": {"zh": oz, "en": oe}, "tagline": {"zh": tz, "en": te},
        "voice": {"language": lang, "brief": brief, "introLine": line},
        "look": src,
        "image": f"library/claude-casting-2026-10-07/final/CC-{cc}.png",
    })
assert len(out) == 95, len(out)
json.dump({"note": "95 new faces cast by Claude, 2026-10. Facts invented with the Owner's approval; first public roster, may change in later versions.", "actors": out},
          open(os.path.join(HERE, "new-faces-2026-10.json"), "w"), ensure_ascii=False, indent=1)
print(len(out), "actors;", sum(a['voice']['language']=='zh' for a in out), "zh voices")
