import { readFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { execFileSync } from "node:child_process";
import { isDeepStrictEqual } from "node:util";
import { loadActorProjection } from "./actor-data.ts";
import { writeTransaction } from "../assets/file-transaction.ts";

const header =
  "// Generated by tools/site/generate-actor-data.ts from media-pack. Do not edit by hand.\n";
export async function generatedActorFiles(root = process.cwd()): Promise<Record<string, string>> {
  const data = await loadActorProjection(root);
  const files: Record<string, string> = {};
  for (const actor of data.active) {
    files[`src/content/actors/${actor.slug}/profile.ts`] =
      `${header}import type { Actor } from "../shared.ts";\nexport const profile: Actor = ${JSON.stringify(actor, null, 2)};\n`;
  }
  files["src/content/actors/active.generated.ts"] =
    `${header}import type { Actor } from "./shared.ts";\n${data.active.map((actor, index) => `import { profile as actor${index} } from "./${actor.slug}/profile.ts";`).join("\n")}\nexport const ACTIVE_ACTORS: Actor[] = [${data.active.map((_, index) => `actor${index}`).join(",")}];\n`;
  files["src/content/actors/new-face-profiles.generated.ts"] =
    `${header}import type { Actor } from "./shared.ts";\nexport const NEW_FACE_ACTORS: Actor[] = ${JSON.stringify(data.newcomers, null, 2)};\n`;
  files["src/content/official-samples.generated.ts"] =
    `${header}export type OfficialSample = {slug:string;tools:string[];images:string[];poster:string;video:string;approvedOn:string};\nexport const OFFICIAL_SAMPLES: OfficialSample[] = ${JSON.stringify(data.samples, null, 2)};\n`;
  for (const [file, source] of Object.entries(files)) {
    files[file] = execFileSync(
      path.resolve("node_modules/.bin/oxfmt"),
      ["--stdin-filepath", file],
      { input: source, encoding: "utf8" },
    );
  }
  // Only this field is generated. Ingestion owns all image/voice delivery fields.
  for (const actor of data.active) {
    const file = `src/content/actors/${actor.slug}/assets.json`;
    const current = await readFile(path.join(root, file), "utf8");
    const manifest = JSON.parse(current);
    if (manifest.slug !== actor.slug || !Array.isArray(manifest.items))
      throw new Error(`Invalid asset manifest: ${file}`);
    files[file] = isDeepStrictEqual(manifest.looks, data.looks[actor.slug])
      ? current
      : `${JSON.stringify({ ...manifest, looks: data.looks[actor.slug] }, null, 2)}\n`;
  }
  return files;
}
export async function generateActorData(root = process.cwd(), check = false) {
  const files = await generatedActorFiles(root);
  const changes: { path: string; bytes: Uint8Array }[] = [];
  for (const [file, contents] of Object.entries(files)) {
    const target = path.join(root, file);
    let actual: string | undefined;
    try {
      actual = await readFile(target, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    if (actual === contents) continue;
    if (check)
      throw new Error(
        `Generated data ${actual === undefined ? "missing" : "drift"}: ${file}; run pnpm data:generate`,
      );
    changes.push({ path: target, bytes: Buffer.from(contents) });
  }
  await writeTransaction(changes);
  return Object.keys(files);
}
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const files = await generateActorData(process.cwd(), process.argv.includes("--check"));
  process.stdout.write(
    `${process.argv.includes("--check") ? "checked" : "generated"} ${files.length} actor/sample outputs\n`,
  );
}
