// Generated by tools/site/generate-actor-data.ts from media-pack. Do not edit by hand.
import type { Actor } from "../shared.ts";
export const profile: Actor = {
  slug: "ma-le",
  nameEn: "Ma Le",
  nameCn: "马乐",
  tagline: {
    en: "His smile starts on one side. Short permed curls.",
    zh: "一边嘴角先笑，头发烫成小卷。",
  },
  status: "active",
  gender: "male",
  age: 24,
  heightCm: 175,
  portrait: "/media/assets/ma-le/turnaround.front.webp",
  spec: [
    {
      id: "age",
      label: {
        en: "Age",
        zh: "年龄",
      },
      value: {
        en: "24",
        zh: "24 岁",
      },
    },
    {
      id: "height",
      label: {
        en: "Height",
        zh: "身高",
      },
      value: {
        en: "175 cm",
        zh: "175 cm",
      },
    },
    {
      id: "origin",
      label: {
        en: "From",
        zh: "籍贯",
      },
      value: {
        en: "Nanning, Guangxi",
        zh: "广西南宁",
      },
    },
    {
      id: "language",
      label: {
        en: "Speaks",
        zh: "语言",
      },
      value: {
        en: "Chinese",
        zh: "中文",
      },
    },
  ],
  note: {
    en: "Ma Le is an AI actor at SWIMMER PARTY. He is from Nanning, Guangxi, 24 years old and 175 cm tall. His lean face, curly permed black hair and one-sided smile are his signature features.",
    zh: "马乐是 SWIMMER PARTY 的 AI 演员，来自广西南宁，24 岁，身高 175 厘米。瘦长的脸、卷烫黑发和一边先扬起的嘴角是他鲜明的特征。",
  },
  promptSeed:
    "3D feature-animation man of East Asian appearance, 24, from Nanning, Guangxi, 175 cm, slim and long-limbed; lean face, curly permed black hair, one-sided smile that starts at one corner of the mouth, bright playful eyes; realistic adult proportions, about 7 heads tall. Unmistakably CG, never photoreal.",
  version: "1.0.0",
  versionDate: "2026-10-09",
  versionNote: {
    en: "First release: 55 images and 6 voice clips.",
    zh: "首次上线：55 张图片和 6 段声音。",
  },
  voiceLanguage: "zh",
};
