// Generated by tools/generate-actor-data.ts from media-pack. Do not edit by hand.
import type { Actor } from "../shared.ts";
export const profile: Actor = {
  slug: "tang-yunqiu",
  nameEn: "Tang Yunqiu",
  nameCn: "唐韵秋",
  tagline: {
    en: "The timid maid on camera. The one running the set off it.",
    zh: "镜头前是胆小的女佣，镜头后整个片场归她管。",
  },
  status: "active",
  gender: "female",
  age: 43,
  heightCm: 163,
  portrait: "/media/assets/tang-yunqiu/turnaround.front.webp",
  spec: [
    {
      id: "age",
      label: {
        en: "Age",
        zh: "年龄",
      },
      value: {
        en: "43",
        zh: "43 岁",
      },
    },
    {
      id: "height",
      label: {
        en: "Height",
        zh: "身高",
      },
      value: {
        en: "163 cm",
        zh: "163 cm",
      },
    },
    {
      id: "origin",
      label: {
        en: "From",
        zh: "籍贯",
      },
      value: {
        en: "Chongqing",
        zh: "重庆",
      },
    },
    {
      id: "language",
      label: {
        en: "Speaks",
        zh: "语言",
      },
      value: {
        en: "Chinese",
        zh: "中文",
      },
    },
  ],
  note: {
    en: "Tang Yunqiu is an AI actress at SWIMMER PARTY. She is from Chongqing, 43 years old and 163 cm tall. She plays He Jie in Journey to the East and also appears in Modern Freaks.",
    zh: "唐韵秋是 SWIMMER PARTY 的 AI 演员，重庆人，43 岁，身高 163 厘米。她在《东游记》里演何姐，也出演《摩登怪咖》。",
  },
  promptSeed:
    "3D feature-animation woman, 43, Chinese, from Chongqing, 163 cm, slim-average build; gentle smile lines, faint crow's feet, noticeably full lips; dark brown shoulder-length waves worn down with a few fine grey strands; noticeably enlarged expressive eyes, smooth stylized skin, hair in clean grouped clumps; realistic adult proportions, about 7 heads tall. Unmistakably CG, never photoreal.",
  version: "1.1.0",
  versionDate: "2026-10-08",
  versionNote: {
    en: "Voice added: 7 clips.",
    zh: "加入声音：7 段。",
  },
  versionHistory: [
    {
      version: "1.0.0",
      date: "2026-10-05",
      note: {
        en: "First release: 63 images.",
        zh: "首次发布：63 张图片。",
      },
    },
  ],
  voiceLanguage: "zh",
};
