// Generated by tools/site/generate-actor-data.ts from media-pack. Do not edit by hand.
export type OfficialSample = {
  slug: string;
  tools: string[];
  images: string[];
  poster: string;
  video: string;
  approvedOn: string;
};
export const OFFICIAL_SAMPLES: OfficialSample[] = [
  {
    slug: "tang-yunqiu",
    tools: ["ChatGPT", "Grok"],
    images: [
      "/media/works/samples/tang-yunqiu/image-01.webp",
      "/media/works/samples/tang-yunqiu/image-02.webp",
    ],
    poster: "/media/works/samples/tang-yunqiu/image-01.webp",
    video: "/media/works/samples/tang-yunqiu/video-01.mp4",
    approvedOn: "2026-10-09",
  },
  {
    slug: "misha-luo",
    tools: ["ChatGPT", "Grok"],
    images: [
      "/media/works/samples/misha-luo/image-01.webp",
      "/media/works/samples/misha-luo/image-02.webp",
    ],
    poster: "/media/works/samples/misha-luo/image-01.webp",
    video: "/media/works/samples/misha-luo/video-01.mp4",
    approvedOn: "2026-10-09",
  },
  {
    slug: "zhang-qiang",
    tools: ["ChatGPT", "Grok"],
    images: [
      "/media/works/samples/zhang-qiang/image-01.webp",
      "/media/works/samples/zhang-qiang/image-02.webp",
    ],
    poster: "/media/works/samples/zhang-qiang/image-01.webp",
    video: "/media/works/samples/zhang-qiang/video-01.mp4",
    approvedOn: "2026-10-09",
  },
  {
    slug: "chen-wei",
    tools: ["ChatGPT", "Grok"],
    images: [
      "/media/works/samples/chen-wei/image-01.webp",
      "/media/works/samples/chen-wei/image-02.webp",
    ],
    poster: "/media/works/samples/chen-wei/image-01.webp",
    video: "/media/works/samples/chen-wei/video-01.mp4",
    approvedOn: "2026-10-09",
  },
  {
    slug: "yan-lin",
    tools: ["ChatGPT", "Grok"],
    images: ["/media/works/samples/yan-lin/image-01.webp"],
    poster: "/media/works/samples/yan-lin/image-01.webp",
    video: "/media/works/samples/yan-lin/video-01.mp4",
    approvedOn: "2026-10-09",
  },
];
