import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

// "Same actor, different tools" samples. Sources live in media-pack/actors/<slug>.json
// (officialSamples) and media-pack/library/samples/<slug>/; this writes web copies to
// public/media/works/samples/<slug>/ and the typed list the site renders.
type SampleSource = {
  officialSamples?: {
    approvedOn: string;
    tools: string[];
    media: { kind: "image" | "video"; source: string }[];
  };
};

const slugs = ["tang-yunqiu", "misha-luo", "zhang-qiang", "chen-wei", "yan-lin"] as const;
const root = process.cwd();
const samples = [];
for (const slug of slugs) {
  const actor = JSON.parse(
    await readFile(path.join(root, "media-pack", "actors", `${slug}.json`), "utf8"),
  ) as SampleSource;
  const source = actor.officialSamples;
  const imageItems = source?.media.filter((item) => item.kind === "image") ?? [];
  const video = source?.media.find((item) => item.kind === "video");
  if (
    !source ||
    ![1, 2].includes(imageItems.length) ||
    !video ||
    source.media.length !== imageItems.length + 1
  )
    throw new Error(`${slug}: officialSamples must list one or two images and one video`);
  const outDir = path.join(root, "public", "media", "works", "samples", slug);
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });
  const imagePaths: string[] = [];
  for (const [index, item] of imageItems.entries()) {
    const name = `image-0${index + 1}.webp`;
    await sharp(path.join(root, "media-pack", item.source))
      .resize({ width: 720, withoutEnlargement: true })
      .webp({ quality: 82 })
      .toFile(path.join(outDir, name));
    imagePaths.push(`/media/works/samples/${slug}/${name}`);
  }
  await copyFile(path.join(root, "media-pack", video.source), path.join(outDir, "video-01.mp4"));
  samples.push({
    slug,
    tools: source.tools,
    images: imagePaths,
    // The video opens on the first scene image, so it doubles as the poster.
    poster: imagePaths[0]!,
    video: `/media/works/samples/${slug}/video-01.mp4`,
    approvedOn: source.approvedOn,
  });
}

const output = `// Generated by tools/generate-official-samples.ts from media-pack/actors/*.json. Do not edit by hand.
export type OfficialSample = {
  slug: string;
  tools: string[];
  images: string[];
  poster: string;
  video: string;
  approvedOn: string;
};

export const OFFICIAL_SAMPLES: OfficialSample[] = ${JSON.stringify(samples, null, 2)};

export function officialSampleFor(slug: string): OfficialSample | undefined {
  return OFFICIAL_SAMPLES.find((sample) => sample.slug === slug);
}
`;
await writeFile(path.join(root, "src", "content", "official-samples.generated.ts"), output);
